### ISSUE TITLE
带查询参数访问文章链接时路由可能有点问题

### ISSUE THREAD

**Issue by 88250** [anlingyi/xeblog-api#1]
不带查询参数 GET 访问是 OK 的，比如 https://xeblog.cn/articles/11
但是如果加了查询参数 GET 访问就有点问题了，比如 https://xeblog.cn/articles/11?xxxx=1

提这个问题主要是因为有的站跳转到博客链接的时候会加 utm 参数来方便博主区分流量来源，加了参数就访问不到了。

**Comment by anlingyi** [comment]
是的，确实有这个问题，感谢提醒！
